import Section1 from "@/Components/Section1";
import Section2 from "@/Components/Section2";
import Section3 from "@/Components/Section3";
import Section4 from "@/Components/Section4";

import Layout from "@/Layout/Layout";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/author/author1.jpg" />
      </Head>
      <Layout>
        <Section1 />
        <Section2 />
        <Section3 />
        <Section4 />
      </Layout>
    </>
  );
}
